### ISSUE TITLE
Nifti to surface does not work

### ISSUE THREAD

**Issue by seralouk** [danjgale/reg-fusion#4]
Hello,

First of all, thanks for this amazing repo.

I have a 3D nifti file that I would like to project to the fsaverage surface for a nice visualization output.
My nifti file is already in MNI space.

I have tried the following but the output an empty nii.gz files.

```
lh, rh = vol_to_fsaverage("/Users/makis/Desktop/stat_map.nii", 'output', template_type='MNI152_orig')
```
How can I solve this issue?

Data:https://easyupload.io/260ldc
Pass: makis

**Comment by danjgale** [comment]
Hi @seralouk, 

Thanks for opening this issue and providing the data. I tested this out with the CLI and `vol_to_fsaverage` and tried to replicate your problem, but couldn't. Here are the commands I ran:

CLI:
`regfusion -s stat_map.nii -o output`

And with `vol_to_fsaverage`:
`lh, rh = vol_to_fsaverage("stat_map.nii", 'output', template_type='MNI152_orig')`

The output viewed in freeview:

![Screenshot from 2021-03-20 11-41-02](https://user-images.githubusercontent.com/14634382/111875785-f33b6d80-8971-11eb-8a90-54385445c23f.png)

So, it seems to be working as expected on my end. I'm running this on a Linux machine (Ubuntu 20.04). 

However, when checked your file I noticed it included several NaNs, which were also flagged by freeview (18542 vertices in the left hemisphere, 17465 vertices in the right hemisphere). Perhaps replacing NaNs in your file might resolve things on your end?

**Comment by danjgale** [comment]
I see that the sign has been flipped -- negative voxels are now positive vertices, and vice versa. I replaced NaN voxels with 0 and still had the same issue. The problem went away after thresholding the map at 0, and the vertices are correctly positive:

![Screenshot from 2021-03-20 12-01-56](https://user-images.githubusercontent.com/14634382/111876216-19faa380-8974-11eb-9a83-9b6e33212945.png)

I haven't come across this issue before because I've been projecting positively thresholded maps. As a temporary fix, perhaps threshold your map? I can investigate further in the meantime

**Comment by danjgale** [comment]
I noticed in the above figure that the sign has been swapped (i.e negative voxels are positive vertices on the surface, and vice versa). This was true even after replacing NaNs with 0.

I checked with two other stat maps I have, each created using different software (nilearn and SPM) and the projections were correct (no sign flipping). So this issue seems to be specific to your file. 

As a temporary fix, you could a) replace the NaNs with 0, and b) flip the sign of voxels `stat_map.nii` so that they would be correct on the surface. Not sure what is causing this issue that is specific to your file.
